INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_DATABASE_MODULE database_module)

FIND_PATH(
    DATABASE_MODULE_INCLUDE_DIRS
    NAMES database_module/api.h
    HINTS $ENV{DATABASE_MODULE_DIR}/include
        ${PC_DATABASE_MODULE_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    DATABASE_MODULE_LIBRARIES
    NAMES gnuradio-database_module
    HINTS $ENV{DATABASE_MODULE_DIR}/lib
        ${PC_DATABASE_MODULE_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(DATABASE_MODULE DEFAULT_MSG DATABASE_MODULE_LIBRARIES DATABASE_MODULE_INCLUDE_DIRS)
MARK_AS_ADVANCED(DATABASE_MODULE_LIBRARIES DATABASE_MODULE_INCLUDE_DIRS)

